Repository DependencyTrack/hyades-frontend, pull requests merged in 2024-08, with the labels that each got.

#110 Bump `@cyclonedx/cyclonedx-library` to 6.11.0
  package-lock.json
  package.json
Labels: dependencies, javascript

#112 Port : Add ability to delete tags and untag projects
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/mixins/permissionsMixin.js
  src/shared/permissions.js
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: enhancement, v4-port

#114 Port: Add EPSS score policy condition
  src/views/policy/PolicyCondition.vue
Labels: enhancement, v4-port

#116 Port : Add `BOM_VALIDATION_FAILED` To Notification Group
  src/views/administration/notifications/Alerts.vue
Labels: enhancement, v4-port

#120 Teams Column
  src/assets/scss/_custom.scss
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/shared/common.js
  src/views/portfolio/projects/ProjectList.vue
Labels: enhancement
