Repository DependencyTrack/hyades-frontend, pull requests merged in 2024-09, with the labels that each got.

#128 Fix "affected projects" table not showing all items
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
Labels: defect

#129 Add maintenance configuration
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/views/administration/AdminMenu.vue
  src/views/administration/configuration/Maintenance.vue
Labels: enhancement

#131 Fix : Update deprecated endpoint usage
  src/views/portfolio/tags/SelectTagModal.vue
Labels: technical debt

#133 Port : Feat/customizable login page
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/views/administration/AdminMenu.vue
  src/views/administration/Administration.vue
  src/views/administration/configuration/WelcomeMessage.vue
  src/views/pages/Login.vue
Labels: enhancement, v4-port

#134 Port : Support inclusion/exclusion of projects from BOM validation with tags
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/configuration/BomFormats.vue
Labels: enhancement, v4-port

#143 Port : Add "limit to tags" option for alerts
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/administration/notifications/Alerts.vue
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
Labels: enhancement, v4-port

#149 Align permissions of tag views with API server
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
Labels: defect
