Repository DependencyTrack/hyades-frontend, pull requests merged in 2024-07, with the labels that each got.

#75 Use `/concise` endpoints for listing projects
  src/views/portfolio/projects/ProjectList.vue
Labels: enhancement

#79 Improve Chinese Localization Quality
  src/i18n/locales/zh.json
Labels: enhancement

#72 Port: Improve German translation
  src/i18n/locales/de.json
Labels: enhancement, v4-port

#73 Add column for vulnerability policy operation mode
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/policy/VulnerabilityPolicyList.vue
Labels: enhancement

#86 Raise baseline Node version to 20
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/i18n.yaml
  .github/workflows/lint.yaml
  .nvmrc
  package-lock.json
  package.json
Labels: technical debt, v4-port

#102 Fix outdated warning when `latestVersion` is empty string
  src/views/globalAudit/VulnerabilityAuditByOccurrence.vue
  src/views/portfolio/projects/ProjectComponents.vue
  src/views/portfolio/projects/ProjectEpss.vue
  src/views/portfolio/projects/ProjectFindings.vue
Labels: defect

#106 Show Badge For Inactive Projects
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/Project.vue
  src/views/portfolio/projects/ProjectList.vue
Labels: enhancement, v4-port

#103 Permission deconstruction
  src/containers/DefaultContainer.vue
  src/mixins/permissionsMixin.js
  src/router/index.js
  src/shared/permissions.js
  src/views/Dashboard.vue
  src/views/administration/AdminMenu.vue
  src/views/administration/Administration.vue
  src/views/policy/LicenseGroupList.vue
  src/views/policy/PolicyCondition.vue
  src/views/policy/PolicyList.vue
  src/views/policy/PolicyManagement.vue
  src/views/policy/VulnerabilityPolicyList.vue
  src/views/portfolio/licenses/License.vue
  src/views/portfolio/licenses/LicenseList.vue
  src/views/portfolio/projects/ComponentDashboard.vue
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/FindingAudit.vue
  src/views/portfolio/projects/ProjectAddComponentModal.vue
  src/views/portfolio/projects/ProjectComponents.vue
  src/views/portfolio/projects/ProjectDashboard.vue
  src/views/portfolio/projects/ProjectDetailsModal.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/projects/ProjectList.vue
  src/views/portfolio/projects/ProjectPropertiesModal.vue
  src/views/portfolio/projects/ServiceDashboard.vue
  src/views/portfolio/projects/ServiceDetailsModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Labels: enhancement
