Repository DependencyTrack/hyades-frontend, pull requests merged in 2025-01, with the labels that each got.

#207 Add project inactiveSince timestamp
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/projects/ProjectDetailsModal.vue
Labels: enhancement

#197 Port: Add `.gitattributes` to fix prettier behavior on Windows
  .gitattributes
Labels: dx, v4-port

#200 Port: Fix creation of multiple projects without reloading page
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
Labels: defect, v4-port

#198 Port: Fix state of sidebar not being saved for non-`SNAPSHOT` versions
  src/containers/DefaultContainer.vue
Labels: defect, v4-port

#201 Port: Always display project nodes in dependency graph using name and version
  src/views/portfolio/projects/ProjectDependencyGraph.vue
Labels: defect, v4-port

#199 Port: Fix OIDC users not being displayed in Team view
  src/views/administration/accessmanagement/Teams.vue
Labels: defect, v4-port

#218 Port : Fix breadcrumbs navigation being broken for non-english languages
  src/containers/DefaultContainer.vue
  src/router/index.js
Labels: defect, v4-port

#217 Port : Fix missing URI encoding of tag names
  src/views/portfolio/tags/TagList.vue
  src/views/portfolio/tags/TaggedNotificationRuleListModal.vue
  src/views/portfolio/tags/TaggedPoliciesListModal.vue
  src/views/portfolio/tags/TaggedProjectListModal.vue
Labels: defect, v4-port

#216 Port : Fix: "Add Version" Create Button Should Be Inactive Until Version Provided
  src/views/portfolio/projects/ProjectAddVersionModal.vue
Labels: defect, v4-port

#215 Port : Fix config update for welcome message
  src/views/administration/configuration/WelcomeMessage.vue
Labels: defect, v4-port

#220 Port : Fix caching issues upon upgrade
  docker/etc/nginx/conf.d/default.conf
Labels: defect, v4-port

#221 Port : Fix tags with special characters breaking the tags table
  src/views/portfolio/tags/TagList.vue
Labels: defect, v4-port

#222 Port : Fix missing URI encoding for vulnerability IDs
  src/views/globalAudit/VulnerabilityAuditByOccurrence.vue
  src/views/globalAudit/VulnerabilityAuditGroupedByVulnerability.vue
  src/views/portfolio/projects/ProjectFindings.vue
  src/views/portfolio/vulnerabilities/AffectedProjects.vue
  src/views/portfolio/vulnerabilities/Vulnerability.vue
  src/views/portfolio/vulnerabilities/VulnerabilityCreateVulnerabilityModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Labels: defect, v4-port

#223 Port : Improve russian translation
  src/i18n/locales/ru.json
Labels: enhancement, v4-port

#202 Port: Add support for serving from custom path
  .dockerignore
  docker/Dockerfile.alpine
  docker/docker-compose.yml
  docker/etc/nginx/templates/default.conf.template
  public/index.html
  public/static/oidc-callback.html
  src/views/pages/Login.vue
  vue.config.js
Labels: enhancement, v4-port

#171 Port : Global Audit View: Policy Violations
  src/containers/DefaultContainer.vue
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/router/index.js
  src/shared/utils.js
  src/views/audit/PolicyViolationAudit.vue
Labels: enhancement, v4-port

#226 Port : Prefill *Team* input in *Create Project* dialog
  src/views/portfolio/projects/ProjectCreateProjectModal.vue
Labels: defect, v4-port

#228 Port : Add buttons to add/delete/edit *Affected Components* of internal vulnerabilities
  src/i18n/locales/de.json
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/hi.json
  src/i18n/locales/it.json
  src/i18n/locales/ja.json
  src/i18n/locales/pl.json
  src/i18n/locales/pt-BR.json
  src/i18n/locales/pt.json
  src/i18n/locales/ru.json
  src/i18n/locales/uk-UA.json
  src/i18n/locales/zh.json
  src/views/portfolio/vulnerabilities/AddAffectedComponentModal.vue
  src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Labels: enhancement, v4-port

#230 Fix loss of permission selection for managed users when switching pages
  src/views/administration/accessmanagement/ManagedUsers.vue
  src/views/administration/accessmanagement/SelectPermissionModal.vue
Labels: defect

#233 Port : Fix NGINX ipv6 listening
  docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Labels: defect, v4-port

#234 Port : Show component properties to users with `VIEW_PORTFOLIO` permission
  src/views/portfolio/projects/ComponentDetailsModal.vue
  src/views/portfolio/projects/ComponentPropertiesModal.vue
Labels: defect, v4-port
